N=1024;
f1=1;f2=10;f3=30;f4=50;
FS=200;
n=0:N-1;
x=sin(2*pi*f1*n/FS);
y1=0.5*sin(2*pi*f2*n/FS);
y2=0.25*sin(2*pi*f3*n/FS);
y3=0.1*sin(2*pi*f4*n/FS);
t=[1:N]*(1/FS);
figure(1);
subplot(4,1,1);
plot(t,x);
title("Sinwave of Frequency");
xlabel('Time, [s]');
ylabel('Amplitude');
grid;
subplot(4,1,2);
plot(t,y1);
title("Sinwave of Frequency");
xlabel('Time, [s]');
ylabel('Amplitude');
grid;
subplot(4,1,3);
plot(t,y2);
title("Sinwave of Frequency");
xlabel('Time, [s]');
ylabel('Amplitude');
grid;
subplot(4,1,4);
plot(t,y3);
title("Sinwave of Frequency");
xlabel('Time, [s]');
ylabel('Amplitude');
grid;

Rxx=autom(x);
Ry1=autom(y1);
Ry2=autom(y2);
Ry3=autom(y3);
figure(2);
subplot(4,1,1);
plot(Rxx);
grid;
title('Autocorrelation function');
xlabel('lags');
ylabel('Autocorrelation');

subplot(4,1,2);
plot(Ry1);
grid;
title('Autocorrelation function');
xlabel('lags');
ylabel('Autocorrelation');

subplot(4,1,3);
plot(Ry2);
grid;
title('Autocorrelation function');
xlabel('lags');
ylabel('Autocorrelation');

subplot(4,1,4);
plot(Ry3);
grid;
title('Autocorrelation function');
xlabel('lags');
ylabel('Autocorrelation');